name: Deploy to EC2

on:
  push:
    branches:
      - master # Or the branch you use to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/my-key.pem ubuntu@${{ secrets.EC2_IP }} << EOF
            cd /home/ubuntu/bus-tracking
            git pull origin master
            composer install --no-interaction
            php artisan migrate --force
            sudo systemctl restart nginx
          EOF
